### ISSUE TITLE
Reloading while a battle tower fight is happening causes a server crash

### ISSUE THREAD

**Issue by nicholasrobertm** [EnvyWare/EnvyBattleTower#1]
```
java.lang.NullPointerException: Exception in server tick loop
        at com.envyful.battle.tower.player.BattleTowerAttribute.getRandomLeaderTeam(BattleTowerAttribute.java:217) ~[envybattletower:?] {re:classloading}
        at com.envyful.battle.tower.player.BattleTowerAttribute.beginBattle(BattleTowerAttribute.java:106) ~[envybattletower:?] {re:classloading}
        at com.envyful.battle.tower.player.BattleTowerAttribute.startAttempt(BattleTowerAttribute.java:100) ~[envybattletower:?] {re:classloading}
        at com.envyful.battle.tower.gui.BattleTowerUI.lambda$open$1(BattleTowerUI.java:43) ~[envybattletower:?] {re:classloading}
        at com.envyful.battle.tower.forge.shade.envy.api.forge.gui.item.ForgeSimpleDisplayable.lambda$onClick$1(ForgeSimpleDisplayable.java:68) ~[envybattletower:?] {re:classloading}
        at com.envyful.battle.tower.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener.onServerTick(ServerTickListener.java:29) ~[envybattletower:?] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_425_ServerTickListener_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:101) ~[forge:?] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:785) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}```

**Comment by danorris709** [comment]
Are you sure this didn't happen as a result of there not being a team defined for the level of battle tower that was reached?

(`BattleTowerConfig.PokePaste random = this.manager.getConfig().getTeamPossibilities(this.currentFloor).getTeams().getWeightedSet().getRandom();`)
